services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

networks:
  backend:
    name: backend
    driver: bridge
